name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via FTPS to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.hostinger_host }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.HOSTINGER_FTPS_PORT || '21' }}
          local-dir: ./
          server-dir: /
          log-level: verbose
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github/**
            **/.vscode/**
            **/node_modules/**

      - name: Verify deployed file checksum
        run: |
          echo "Downloading deployed HTML and computing sha256..."
          sudo apt-get update && sudo apt-get install -y curl coreutils
          curl -sS https://zaptoroai.com/ZAPTOROAI.html -o /tmp/deployed.html || true
          sha_deployed=$(sha256sum /tmp/deployed.html 2>/dev/null | awk '{print $1}' || echo "")
          sha_local=$(sha256sum ZAPTOROAI.html | awk '{print $1}')
          echo "deployed: $sha_deployed"
          echo "local:    $sha_local"
          if [ "$sha_deployed" = "$sha_local" ]; then echo "CHECKSUM MATCH: deployed file matches repo"; else echo "CHECKSUM MISMATCH: deployed file does NOT match repo"; exit 1; fi