name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.hostinger_host }}
          # Username is now read from a secret for safety. Add a repository secret named HOSTINGER_USER
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          # Deploy path for your Hostinger account
          server-dir: /public_html/
          protocol: ftp
          port: 21
          timeout: 60000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.vscode/**